### ISSUE TITLE
Error when trying to add plugin

### ISSUE THREAD

**Issue by UROwLImP** [cholmes/qgis_plugin_gpq_downloader#44]
Couldn't load plugin 'qgis_plugin_gpq_downloader' 

ModuleNotFoundError: No module named 'duckdb' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python/plugins\qgis_plugin_gpq_downloader\__init__.py", line 1, in 
    from .qgis_plugin_gpq_downloader import QgisPluginGeoParquet
  File "C:\PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python/plugins\qgis_plugin_gpq_downloader\qgis_plugin_gpq_downloader.py", line 13, in 
    import duckdb
  File "C:\PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'duckdb'

Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.12-Prizren Prizren, eeb6af3638 

Python Path:
C:/PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python
C:/Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python
C:/Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python/plugins
C:/PROGRA~1/QGIS 3.34.12/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS 3.34.12\apps\grass\grass84\etc\python
C:\Users\Doug Hall\Documents
C:\Program Files\QGIS 3.34.12\bin\python312.zip
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\DLLs
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\Lib
C:\Program Files\QGIS 3.34.12\bin
C:\PROGRA~1\QGIS 3.34.12\apps\Python312
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.34.12\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python
C:\Users\Doug Hall\AppData\Roaming\QGIS\QGIS3\profiles\Doug_2024\python\plugins\assets\external\xmltodict-0.13.0-py2.py3-none-any.whl
C:\Users\Doug Hall\AppData\Roaming\QGIS\QGIS3\profiles\Doug_2024\python\plugins\assets\external\aenum-3.1.11-py3-none-any.whl

**Comment by gudeso2023** [comment]
Same issues, can't install it nor in my mac or Windows laptop

**Comment by mtravis** [comment]
The thing that sticks out to me here is this line. Are you using virtual machines? Could it be that you're getting blocked somewhere in your organisation from using pip? The plugin uses that to install DuckDB if you don't have it.


```
C:\Users/Doug Hall/AppData/Roaming/QGIS/QGIS3\profiles\Doug_2024/python/plugins\qgis_plugin_gpq_downloader_init.py", line 1,
```

Just a thought as there are other things it could be but this stands out to me as I used to have similar issues.

**Comment by cholmes** [comment]
@UROwLImP - sorry, I didn't see this until now. 

@gudeso2023 and @UROwLImP  - could you try to first install https://plugins.qgis.org/plugins/qduckdb/ on windows and see if that helps?

@mtravis - your guess seems likely, that some the network could be blocked. I think we should do #42 and then link to a clear page that explains the options for installing it.

**Comment by UROwLImP** [comment]
@cholmes - Installed flawlessly after following your suggestion to install DuckDB first. Thanks very much!

**Comment by UROwLImP** [comment]
> The thing that sticks out to me here is this line. Are you using virtual machines? Could it be that you're getting blocked somewhere in your organisation from using pip? The plugin uses that to install DuckDB if you don't have it.

@mtravis Not using a VM, and I'm not aware of any organisational restrictions - I'm operating in a very relaxed IT environment.

**Comment by cholmes** [comment]
> @cholmes - Installed flawlessly after following your suggestion to install DuckDB first. Thanks very much!

Ok, cool. I had removed that from the instructions as I was hoping that the new version would remove the need for that.

Actually, can you check and share what version of the plugin you have installed? The lines on the stack trace you shared makes me think it may have been a 0.2.1, before we added the functionality to automatically install it. It was released by then, but perhaps the local repo wasn't updated...

**Comment by UROwLImP** [comment]
Showing version 0.3.1

I just did a clean install of the current LTR version, and tried to add the plugin. Failed with the following:

Couldn't load plugin 'qgis_plugin_gpq_downloader' due to an error when calling its classFactory() method
ModuleNotFoundError: No module named 'duckdb'
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\__init__.py", line 78, in classFactory
    from .qgis_plugin_gpq_downloader import QgisPluginGeoParquet
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\qgis_plugin_gpq_downloader.py", line 15, in
    import duckdb
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'duckdb'

Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)]
QGIS version: 3.34.13-Prizren Prizren, 222b5995
Python Path:

  *   C:\Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\ext-libs\duckdb
  *   C:\Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_plugin_gpq_downloader\ext-libs
  *   C:/PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python
  *   C:/Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
  *   C:/Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
  *   C:/PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins
  *   C:\PROGRA~1\QGIS33~1.13\apps\grass\grass84\etc\python
  *   C:\Users\dougl\Documents
  *   C:\Program Files\QGIS 3.34.13\bin\python312.zip
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\DLLs
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib
  *   C:\Program Files\QGIS 3.34.13\bin
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\win32
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\win32\lib
  *   C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\Pythonwin
  *   C:/Users/dougl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
  *   C:\Users\dougl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\FeatureGridCreator
C:\Users\dougl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by cholmes** [comment]
Ok, great. Thanks for checking. I have no idea what actually went wrong, but I'll at least make it so there's a much nicer error message that tells how to resolve it. And will investigate if there's ways we can automatically include qduckdb. Thanks so much for the report, and for trying it out - it helps things get better!

**Comment by jaakla** [comment]
I had similar/same issue with macos (ARM64), managed to install duckdb to QGIS python with these two commands:
```
cd /Applications/QGIS.app/Contents/MacOS/bin
sudo ./python3 -m pip install duckdb
```
Plugin itself works, but stock macos QGIS does not read geoparquet, conda installer for qgis allowing it seems to be stalled. I could not use conda myself anyway as it requires paid enterprise seat license for my compute. Here another plugin feature to actually read geoparquet (via same duckdb perhaps) without specific gdal requirement would come super handy.

**Comment by mtravis** [comment]
> I had similar/same issue with macos (ARM64), managed to install duckdb to QGIS python with these two commands:
> 
> ```
> cd /Applications/QGIS.app/Contents/MacOS/bin
> sudo ./python3 -m pip install duckdb
> ```
> 
> Plugin itself works, but stock macos QGIS does not read geoparquet, conda installer activity for qgis seems to be stalled. I could not use conda myself anyway as it requires paid enterprise seat license for my company computer. Here another plugin feature to actually read geoparquet (via same duckdb perhaps) without specific gdal requirement would come super handy.

@jaakla you could try installing QGIS on Mac using pixi as shown in this [gist](https://gist.github.com/mtravis/5ad71651177af647eabb77d17cf6aad7)

You're going to need GDAL with the pyarrow/parquet library as that's what QGIS uses under the hood to render Geoparquet. There's no getting around that AFAIK

**Comment by cholmes** [comment]
> I had similar/same issue with macos (ARM64), managed to install duckdb to QGIS python with these two commands:

The 0.4.0 release hopefully does not require those two commands, we made some improvements so its a bit more robust on automatic installation.

> Plugin itself works, but stock macos QGIS does not read geoparquet, conda installer activity for qgis seems to be stalled. 

I've been following up on this, there is now some progress and momentum on new installers, see https://github.com/qgis/QGIS/pull/60039 And I've been talking to the author of that and he's up to get geoparquet support in there by default.

> I could not use conda myself anyway as it requires paid enterprise seat license for my company computer.

Curious can you use mamba? I may just start recommending that. It's much faster anyways. 

> Here another plugin feature to actually read geoparquet (via same duckdb perhaps) without specific gdal requirement would come super handy

That is a creative idea. I think it's beyond my skill, as I'd guess there's a lot of intricacies to actually hook up to the renderer. Hmmm... I don't think the UI would be great, but I could see functionality to just convert through a plugin like this does - enter a local file location and do the conversion to fgb or geopackage using DuckDB. Not quite as nice, but then wouldn't need need to try to figure out the renderer.

Though I feel it gets a bit beyond the scope of this plugin. I'm working on https://github.com/cholmes/geoparquet-tools and hope to expose that stuff through a plugin - could add 'convert' there. Though I'm thinking of exposing at least the 'check all' functionality from there to here, so you can get a little report on the data you may download through here.

Going to close this, in favor of newer issues, since there have been some improvements (though I suspect it's still not 'perfect')
